# MQTT Server settings
mqttserver:
  hostname: localhost
  port: 1883
  default_channel: info

# for passive command on/off
event_on:
  channel: /info/on
  message: on
event_off:
  channel: /info/off
  message: off